### ISSUE TITLE
2.93 error trying to insert a model

### ISSUE THREAD

**Issue by spiraloid** [jayanam/fast-sculpt#11]
hello,  can't get this to work in 2.93

`WARN (bpy.rna): C:\Users\blender\git\blender-v293\blender.git\source\blender\python\intern\bpy_rna.c:8416 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
WARN (bpy.rna): C:\Users\blender\git\blender-v293\blender.git\source\blender\python\intern\bpy_rna.c:8416 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
Python: Traceback (most recent call last):
  File "C:\Users\bay\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fast-sculpt-master\fsc_add_object_op.py", line 88, in modal
    self.add_object(context, mouse_pos)
  File "C:\Users\bay\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fast-sculpt-master\fsc_add_object_op.py", line 115, in add_object
    hit, loc_hit, norm, face, *_ = scene.ray_cast(context.view_layer, origin, view_vector)
TypeError: Scene.ray_cast(): error with argument 1, "depsgraph" -  Function.depsgraph expected a Depsgraph type, not ViewLayer

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\bay\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fast-sculpt-master\fsc_add_object_op.py", line 88, in modal
    self.add_object(context, mouse_pos)
  File "C:\Users\bay\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fast-sculpt-master\fsc_add_object_op.py", line 115, in add_object
    hit, loc_hit, norm, face, *_ = scene.ray_cast(context.view_layer, origin, view_vector)
TypeError: Scene.ray_cast(): error with argument 1, "depsgraph" -  Function.depsgraph expected a Depsgraph type, not ViewLayer

location: <unknown location>:-1
`

**Comment by Derpford** [comment]
I'm also having issues inserting a mesh in 2.93.
```
bpy.ops.sculpt.sculptmode_toggle()
bpy.ops.object.fsc_add_object()
Python: Traceback (most recent call last):
  File "C:\Users\Breez\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fast-sculpt-master\fsc_add_object_op.py", line 88, in modal
    self.add_object(context, mouse_pos)
  File "C:\Users\Breez\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fast-sculpt-master\fsc_add_object_op.py", line 115, in add_object
    hit, loc_hit, norm, face, *_ = scene.ray_cast(context.view_layer, origin, view_vector)
TypeError: Scene.ray_cast(): error with argument 1, "depsgraph" -  Function.depsgraph expected a Depsgraph type, not ViewLayer

location: <unknown location>:-1

```
